Add gradle tests
OpenLiberty/liberty-dev-tools-eclipse pull request #55
Opened 2022-06-06 20:24 UTC by awisniew90

Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>

2022-06-08 13:03 UTC, scottkurz commented on tests/resources/applications/gradle/liberty-gradle-test-app/src/main/java/test/maven/liberty/web/app/HelloServlet.java
> +/*******************************************************************************
Let's stick to EPL 2.0 rather than dragging in different licenses.   Since it's IBM copyright (and Apache 2) we can relicense to EPL 2

2022-06-08 13:22 UTC, scottkurz commented on tests/resources/files/apps/maven/liberty-maven-test-app/pom.xml
>              <scope>test</scope>
Why is there a separate test/resources/files dir with pom and build.gradle ?  I remember there being a 'files' dir to add in the mvnw.

2022-06-08 13:23 UTC, scottkurz commented on tests/src/liberty/tools/test/it/utils/LibertyPluginTestUtils.java
> +package liberty.tools.test.it.utils;
copyright

2022-06-08 13:24 UTC, scottkurz commented on tests/src/liberty/tools/test/it/LibertyPluginSWTBotDashboardTest.java
> +package liberty.tools.test.it;
copyright

2022-06-08 13:24 UTC, scottkurz commented on tests/src/liberty/tools/test/it/LibertyPluginSWTBotDashboardTest.java
> +    public void testOpenDashboardUsingMenu() {
Good of you to add

2022-06-08 13:24 UTC, scottkurz commented on tests/src/liberty/tools/test/it/LibertyPluginSWTBotMavenTest.java
> +        LibertyPluginTestUtils.validateApplicationOutcome(MVN_APP_NAME, false);
you can also do a static import of the method(s)

2022-06-08 15:21 UTC, awisniew90 commented on tests/resources/applications/gradle/liberty-gradle-test-app/build.gradle
> +apply plugin: 'liberty'
For this scenario, we are importing the apps into eclipse and want to make sure the "app" populates in the dashboard depending on if the OL plugin is defined. Simpler in this case to have two separate apps that we can tweak independently. At least IMO.  But good point to keep in mind moving forward. We may be able to reuse apps if this begins to grow larger.

2022-06-08 15:46 UTC, scottkurz requested changes

2022-06-08 15:46 UTC, scottkurz commented on tests/resources/applications/gradle/liberty-gradle-test-app/src/main/liberty/config/server.xml
> +<!--
Let's replace the old Apache 2 licenses

2022-06-08 15:46 UTC, scottkurz commented on tests/resources/applications/gradle/liberty-gradle-test-app/src/test/java/test/maven/liberty/web/app/ApplicationTest.java
> + * (c) Copyright IBM Corporation 2017.
copyright

2022-06-08 15:46 UTC, scottkurz commented on tests/resources/applications/gradle/liberty-gradle-test-app/src/test/java/test/maven/liberty/web/app/it/EndpointIT.java
> +/*******************************************************************************
copyright

2022-06-08 21:02 UTC, mezarin reviewed
Hey Adam, i had a few comments, but in a more general sense, using those 3 same test classes you currently have (common, Maven, and Gradle), you could have put all the test on the common class, and have counterpart methods on the other two that just call them with custom parameters. In the most of the cases the parameter to pass would be just the appName. The reason for this comment is that this way we avoid having to separate implementations with similar code. Hope that makes sense.

2022-06-09 13:42 UTC, awisniew90 commented on tests/src/liberty/tools/test/it/LibertyPluginSWTBotMavenTest.java
> +        	// Move build.gradle files
Good catch

2022-06-09 13:44 UTC, awisniew90 commented on tests/src/liberty/tools/test/it/LibertyPluginSWTBotMavenTest.java
> +            original.renameTo(updated);
This method actually "moves" the files rather than copying, so this step is needed to "move" the now _updated_ file back to it's original location.

2022-06-15 19:17 UTC, scottkurz approved these changes
LGTM

2022-06-15 19:54 UTC, merged